name: Build
on:
  # push:
  #  tags:
  #    - '0.1.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '0.1.0'
jobs:

  build-linux:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.build.outputs.artifact-path }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install requirements.txt
      run: |
        set -eux
        python3 -m pip install -r requirements.txt
    - name: Build binary with PyInstaller
      run: |
        set -eux
        python3 -m PyInstaller --onefile --windowed main.py --name lancalc-linux
    - name: List artifacts
      run: |
        set -eux
        tree
    - name: Build artifact output
      id: build
      run: echo "::set-output name=artifact-path::$(pwd)/dist/lancalc-linux"

  build-windows:
    runs-on: windows-latest
    outputs:
      artifact: ${{ steps.build.outputs.artifact-path }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
      - name: Build binary with PyInstaller
        run: |
          python -m PyInstaller --onefile --windowed main.py --name lancalc-windows.exe
      - name: Build artifact output
        id: build
        run: echo "::set-output name=artifact-path::$(pwd)/dist/lancalc-windows.exe"

  build-macos:
    runs-on: macos-latest
    outputs:
      artifact: ${{ steps.build.outputs.artifact-path }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install requirements
        run: |
          python3 -m pip install -r requirements.txt
      - name: Build binary with PyInstaller
        run: |
          python3 -m PyInstaller --onefile --windowed main.py --name lancalc-macos
      - name: List artifacts
        run: |
          set -eux
          ls -lah dist
      - name: Build artifact output
        id: build
        run: echo "::set-output name=artifact-path::$(pwd)/dist/lancalc-macos"

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: dist
    - name: List artifacts
      run: ls -R dist/
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.event.inputs.version }}
        tag_name: ${{ github.event.inputs.version }}
        body: 'Release ${{ github.event.inputs.version }}'
        draft: true
        prerelease: false
        files: |
          dist/lancalc-linux
          dist/lancalc-macos
          dist/lancalc-windows.exe
