name: Build Release
on:
  # push:
  #  tags:
  #    - '0.1.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '0.1.0'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install requirements.txt
      run: |
        set -eux
        python3 -m pip install -r requirements.txt
    - name: Build binary with PyInstaller
      run: |
        set -eux
        python3 -m PyInstaller --onefile --windowed main.py --name lancalc
    - name: List artifacts
      run: |
        set -eux
        tree
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: Linux Release ${{ github.event.inputs.version }}
        tag_name: linux-${{ github.event.inputs.version }}
        body: 'Linux Release ${{ github.event.inputs.version }}'
        draft: true
        prerelease: false
        files: |
          dist/lancalc

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
      - name: Build binary with PyInstaller
        run: |
          python -m PyInstaller --onefile --windowed main.py --name lancalc.exe
      - name: Release Windows
        uses: softprops/action-gh-release@v2
        with:
          name: Windows Release ${{ github.event.inputs.version }}
          tag_name: windows-${{ github.event.inputs.version }}
          body: 'Windows Release ${{ github.event.inputs.version }}'
          draft: true
          prerelease: false
          files: dist/lancalc.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install requirements
        run: |
          python3 -m pip install -r requirements.txt
      - name: Build binary with PyInstaller
        run: |
          python3 -m PyInstaller --onefile --windowed main.py --name lancalc
      - name: List artifacts
        run: |
          set -eux
          ls -lah dist
      - name: Release macOS
        uses: softprops/action-gh-release@v2
        with:
          name: macOS Release ${{ github.event.inputs.version }}
          tag_name: macos-${{ github.event.inputs.version }}
          body: 'macOS Release ${{ github.event.inputs.version }}'
          draft: true
          prerelease: false
          files: dist/lancalc
